package com.linqibin.blog.taxonomy.web;

import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import com.linqibin.blog.common.request.RequestIdUtils;
import com.linqibin.blog.taxonomy.infrastructure.InMemoryCategoryRepository;
import com.linqibin.blog.taxonomy.infrastructure.InMemoryTagRepository;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc(addFilters = false)
class TaxonomyControllerIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private InMemoryCategoryRepository categoryRepository;

    @Autowired
    private InMemoryTagRepository tagRepository;

    @BeforeEach
    void setUp() {
        categoryRepository.clear();
        tagRepository.clear();
    }

    // ==================== Admin Category ====================

    @Test
    void createCategoryEndpointReturnsCreatedCategory() throws Exception {
        mockMvc.perform(post("/api/admin/categories")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Spring Boot",
                                  "slug": "spring-boot",
                                  "description": "Spring Boot tutorials"
                                }
                                """)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "create-category-request-id"))
                .andExpect(status().isCreated())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "create-category-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("create-category-request-id"))
                .andExpect(jsonPath("$.data.name").value("Spring Boot"))
                .andExpect(jsonPath("$.data.slug").value("spring-boot"))
                .andExpect(jsonPath("$.data.description").value("Spring Boot tutorials"));
    }

    @Test
    void createCategoryWithAutoGeneratedSlug() throws Exception {
        mockMvc.perform(post("/api/admin/categories")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Hello World"
                                }
                                """))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.data.slug").value("hello-world"))
                .andExpect(jsonPath("$.data.description").doesNotExist());
    }

    @Test
    void listCategoriesEndpointReturnsAllCategories() throws Exception {
        createCategory("First", "first");
        createCategory("Second", "second");

        mockMvc.perform(get("/api/admin/categories")
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "list-categories-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "list-categories-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("list-categories-request-id"))
                .andExpect(jsonPath("$.data.length()").value(2));
    }

    @Test
    void getCategoryByIdEndpointReturnsCategory() throws Exception {
        UUID categoryId = createCategory("Find Me", "find-me");

        mockMvc.perform(get("/api/admin/categories/" + categoryId)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "get-category-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "get-category-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("get-category-request-id"))
                .andExpect(jsonPath("$.data.id").value(categoryId.toString()))
                .andExpect(jsonPath("$.data.name").value("Find Me"))
                .andExpect(jsonPath("$.data.slug").value("find-me"));
    }

    @Test
    void updateCategoryEndpointUpdatesNameAndDescription() throws Exception {
        UUID categoryId = createCategory("Original", "original-slug");

        mockMvc.perform(put("/api/admin/categories/" + categoryId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Updated Name",
                                  "description": "Updated Description"
                                }
                                """)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "update-category-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "update-category-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("update-category-request-id"))
                .andExpect(jsonPath("$.data.name").value("Updated Name"))
                .andExpect(jsonPath("$.data.description").value("Updated Description"))
                .andExpect(jsonPath("$.data.slug").value("original-slug"));
    }

    @Test
    void updateCategorySlugEndpointChangesSlug() throws Exception {
        UUID categoryId = createCategory("My Category", "old-slug");

        mockMvc.perform(put("/api/admin/categories/" + categoryId + "/slug")
                        .contentType(MediaType.TEXT_PLAIN)
                        .content("new-slug"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.slug").value("new-slug"));
    }

    @Test
    void deleteCategoryEndpointRemovesCategory() throws Exception {
        UUID categoryId = createCategory("Delete Me", "delete-me");

        mockMvc.perform(delete("/api/admin/categories/" + categoryId)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "delete-category-request-id"))
                .andExpect(status().isNoContent())
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "delete-category-request-id"));
    }

    @Test
    void createCategoryWithDuplicateSlugReturnsConflict() throws Exception {
        createCategory("First", "duplicate-slug");

        mockMvc.perform(post("/api/admin/categories")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Second",
                                  "slug": "duplicate-slug"
                                }
                                """)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "duplicate-slug-request-id"))
                .andExpect(status().isConflict())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "duplicate-slug-request-id"))
                .andExpect(jsonPath("$.code").value("DUPLICATE_TAXONOMY_SLUG"))
                .andExpect(jsonPath("$.message").value("slug 已存在: duplicate-slug"))
                .andExpect(jsonPath("$.requestId").value("duplicate-slug-request-id"));
    }

    @Test
    void getMissingCategoryByIdReturnsNotFound() throws Exception {
        UUID randomId = UUID.randomUUID();

        mockMvc.perform(get("/api/admin/categories/" + randomId)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "missing-category-request-id"))
                .andExpect(status().isNotFound())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "missing-category-request-id"))
                .andExpect(jsonPath("$.code").value("TAXONOMY_NOT_FOUND"))
                .andExpect(jsonPath("$.message").value("分类不存在: " + randomId))
                .andExpect(jsonPath("$.requestId").value("missing-category-request-id"));
    }

    @Test
    void createCategoryWithBlankNameReturnsBadRequest() throws Exception {
        mockMvc.perform(post("/api/admin/categories")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": ""
                                }
                                """)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "blank-name-request-id"))
                .andExpect(status().isBadRequest())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "blank-name-request-id"))
                .andExpect(jsonPath("$.code").value("VALIDATION_ERROR"))
                .andExpect(jsonPath("$.requestId").value("blank-name-request-id"));
    }

    // ==================== Admin Tag ====================

    @Test
    void createTagEndpointReturnsCreatedTag() throws Exception {
        mockMvc.perform(post("/api/admin/tags")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Java",
                                  "slug": "java"
                                }
                                """)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "create-tag-request-id"))
                .andExpect(status().isCreated())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "create-tag-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("create-tag-request-id"))
                .andExpect(jsonPath("$.data.name").value("Java"))
                .andExpect(jsonPath("$.data.slug").value("java"));
    }

    @Test
    void createTagWithAutoGeneratedSlug() throws Exception {
        mockMvc.perform(post("/api/admin/tags")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Hello World"
                                }
                                """))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.data.slug").value("hello-world"));
    }

    @Test
    void listTagsEndpointReturnsAllTags() throws Exception {
        createTag("First", "first");
        createTag("Second", "second");

        mockMvc.perform(get("/api/admin/tags")
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "list-tags-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "list-tags-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("list-tags-request-id"))
                .andExpect(jsonPath("$.data.length()").value(2));
    }

    @Test
    void getTagByIdEndpointReturnsTag() throws Exception {
        UUID tagId = createTag("Find Me", "find-me");

        mockMvc.perform(get("/api/admin/tags/" + tagId)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "get-tag-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "get-tag-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("get-tag-request-id"))
                .andExpect(jsonPath("$.data.id").value(tagId.toString()))
                .andExpect(jsonPath("$.data.name").value("Find Me"))
                .andExpect(jsonPath("$.data.slug").value("find-me"));
    }

    @Test
    void updateTagEndpointUpdatesName() throws Exception {
        UUID tagId = createTag("Original", "original-slug");

        mockMvc.perform(put("/api/admin/tags/" + tagId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Updated Name"
                                }
                                """)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "update-tag-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "update-tag-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("update-tag-request-id"))
                .andExpect(jsonPath("$.data.name").value("Updated Name"))
                .andExpect(jsonPath("$.data.slug").value("original-slug"));
    }

    @Test
    void updateTagSlugEndpointChangesSlug() throws Exception {
        UUID tagId = createTag("My Tag", "old-slug");

        mockMvc.perform(put("/api/admin/tags/" + tagId + "/slug")
                        .contentType(MediaType.TEXT_PLAIN)
                        .content("new-slug"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.slug").value("new-slug"));
    }

    @Test
    void deleteTagEndpointRemovesTag() throws Exception {
        UUID tagId = createTag("Delete Me", "delete-me");

        mockMvc.perform(delete("/api/admin/tags/" + tagId)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "delete-tag-request-id"))
                .andExpect(status().isNoContent())
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "delete-tag-request-id"));
    }

    @Test
    void createTagWithDuplicateSlugReturnsConflict() throws Exception {
        createTag("First", "duplicate-slug");

        mockMvc.perform(post("/api/admin/tags")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Second",
                                  "slug": "duplicate-slug"
                                }
                                """)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "duplicate-tag-slug-request-id"))
                .andExpect(status().isConflict())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "duplicate-tag-slug-request-id"))
                .andExpect(jsonPath("$.code").value("DUPLICATE_TAXONOMY_SLUG"))
                .andExpect(jsonPath("$.message").value("slug 已存在: duplicate-slug"))
                .andExpect(jsonPath("$.requestId").value("duplicate-tag-slug-request-id"));
    }

    @Test
    void getMissingTagByIdReturnsNotFound() throws Exception {
        UUID randomId = UUID.randomUUID();

        mockMvc.perform(get("/api/admin/tags/" + randomId)
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "missing-tag-request-id"))
                .andExpect(status().isNotFound())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "missing-tag-request-id"))
                .andExpect(jsonPath("$.code").value("TAXONOMY_NOT_FOUND"))
                .andExpect(jsonPath("$.message").value("标签不存在: " + randomId))
                .andExpect(jsonPath("$.requestId").value("missing-tag-request-id"));
    }

    // ==================== Public Taxonomy ====================

    @Test
    void publicListCategoriesReturnsAllCategories() throws Exception {
        createCategory("Spring Boot", "spring-boot");
        createCategory("Redis", "redis");

        mockMvc.perform(get("/api/public/categories")
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "public-categories-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "public-categories-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("public-categories-request-id"))
                .andExpect(jsonPath("$.data.length()").value(2));
    }

    @Test
    void publicGetCategoryBySlugReturnsCategory() throws Exception {
        createCategory("Spring Boot", "spring-boot");

        mockMvc.perform(get("/api/public/categories/spring-boot")
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "public-category-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "public-category-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("public-category-request-id"))
                .andExpect(jsonPath("$.data.name").value("Spring Boot"))
                .andExpect(jsonPath("$.data.slug").value("spring-boot"));
    }

    @Test
    void publicGetMissingCategoryBySlugReturnsNotFound() throws Exception {
        mockMvc.perform(get("/api/public/categories/non-existent")
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "public-missing-category-request-id"))
                .andExpect(status().isNotFound())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "public-missing-category-request-id"))
                .andExpect(jsonPath("$.code").value("TAXONOMY_NOT_FOUND"))
                .andExpect(jsonPath("$.message").value("分类不存在: non-existent"))
                .andExpect(jsonPath("$.requestId").value("public-missing-category-request-id"));
    }

    @Test
    void publicListTagsReturnsAllTags() throws Exception {
        createTag("Java", "java");
        createTag("Spring", "spring");

        mockMvc.perform(get("/api/public/tags")
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "public-tags-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "public-tags-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("public-tags-request-id"))
                .andExpect(jsonPath("$.data.length()").value(2));
    }

    @Test
    void publicGetTagBySlugReturnsTag() throws Exception {
        createTag("Java", "java");

        mockMvc.perform(get("/api/public/tags/java")
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "public-tag-request-id"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "public-tag-request-id"))
                .andExpect(jsonPath("$.code").value("OK"))
                .andExpect(jsonPath("$.message").value("success"))
                .andExpect(jsonPath("$.requestId").value("public-tag-request-id"))
                .andExpect(jsonPath("$.data.name").value("Java"))
                .andExpect(jsonPath("$.data.slug").value("java"));
    }

    @Test
    void publicGetMissingTagBySlugReturnsNotFound() throws Exception {
        mockMvc.perform(get("/api/public/tags/non-existent")
                        .header(RequestIdUtils.REQUEST_ID_HEADER, "public-missing-tag-request-id"))
                .andExpect(status().isNotFound())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(header().string(RequestIdUtils.REQUEST_ID_HEADER, "public-missing-tag-request-id"))
                .andExpect(jsonPath("$.code").value("TAXONOMY_NOT_FOUND"))
                .andExpect(jsonPath("$.message").value("标签不存在: non-existent"))
                .andExpect(jsonPath("$.requestId").value("public-missing-tag-request-id"));
    }

    // ==================== Helper Methods ====================

    private UUID createCategory(String name, String slug) throws Exception {
        mockMvc.perform(post("/api/admin/categories")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "%s",
                                  "slug": "%s"
                                }
                                """.formatted(name, slug)))
                .andExpect(status().isCreated());

        return categoryRepository.findAll().stream()
                .filter(c -> c.slug().equals(slug))
                .findFirst()
                .orElseThrow()
                .id();
    }

    private UUID createTag(String name, String slug) throws Exception {
        mockMvc.perform(post("/api/admin/tags")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "%s",
                                  "slug": "%s"
                                }
                                """.formatted(name, slug)))
                .andExpect(status().isCreated());

        return tagRepository.findAll().stream()
                .filter(t -> t.slug().equals(slug))
                .findFirst()
                .orElseThrow()
                .id();
    }
}
